site_name: Tourcord docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
  custom_dir: custom_theme

nav:
  - トップページ: index.md
  - 参加者用コマンド:
      - コマンド一覧: member/index.md
  - 運営用コマンド:
      - コマンド一覧: admin/index.md

markdown_extensions:
  - fontawesome_markdown

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
